 Undersampling for regression

In [ ]:
# pip install imbalanced-learn

import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
import seaborn as sns
pd.set_option('display.float_format', '{:.2f}'.format)

df = pd.read_csv("Numeric data (last year work).csv")
df

# I had to choose Python 3.9.13 in order to utilize imblearn library

,Rating,Votes,Meta Score,Year,Duration,Action,Adventure,Animation,Biography,Comedy,...,PG Rating_NC-17,PG Rating_PG,PG Rating_PG-13,PG Rating_Passed,PG Rating_R,PG Rating_TV-14,PG Rating_TV-G,PG Rating_TV-MA,PG Rating_TV-PG,PG Rating_TV-Y7
0,6.50,90000.00,67.00,2023,138,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,7.40,24000.00,66.00,2023,116,0,1,0,0,1,...,0,1,0,0,0,0,0,0,0,0
2,7.00,21000.00,85.00,2023,117,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
3,7.10,56000.00,54.00,2023,157,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,6.60,66000.00,64.00,2023,158,1,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1126,6.30,22000.00,67.00,2021,141,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1127,7.10,172000.00,59.00,2008,112,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
1128,7.60,198000.00,79.00,1986,96,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1129,6.50,71000.00,46.00,1992,104,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
1130,7.10,203000.00,65.00,2017,115,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0