In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv("Numeric data (last year work).csv")

variable = "Rating"

# Calculate the median
median = df[variable].median()

# Calculate MAD
mad = np.median(np.abs(df[variable] - median))

# Define a threshold for noise detection
threshold = 3 * mad

# Detect noise
noise = df[np.abs(df[variable] - median) > threshold]

print("Detected noise using MAD:")
noise

Detected noise using MAD:

,Rating,Votes,Meta Score,Year,Duration,Action,Adventure,Animation,Biography,Comedy,...,PG Rating_NC-17,PG Rating_PG,PG Rating_PG-13,PG Rating_Passed,PG Rating_R,PG Rating_TV-14,PG Rating_TV-G,PG Rating_TV-MA,PG Rating_TV-PG,PG Rating_TV-Y7
165,8.1,448000.0,81.0,2019,152,1,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
264,8.1,432000.0,75.0,1986,89,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
326,8.1,432000.0,92.0,1986,120,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
422,8.1,332000.0,77.0,1995,101,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
447,8.1,443000.0,86.0,2015,118,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
703,8.1,373000.0,90.0,1980,129,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
908,8.1,115000.0,81.0,1984,145,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [ ]:
# Skeptically, I read this analysis
# because I do not consider rating 8.1 
# as an outlier

# But let's check what are the minimum and maximum values of this column

In [7]:
df['Rating'].value_counts()

# well, now I can see that 8.1 can be considered as an outlier

Rating
7.1    95
7.0    73
7.3    69
6.6    69
6.8    67
7.2    67
6.9    67
6.5    66
6.7    59
6.4    54
6.3    52
7.5    51
7.4    48
6.2    48
6.1    48
7.7    45
7.6    45
7.8    37
5.9    23
6.0    18
7.9    16
8.0     7
8.1     7
Name: count, dtype: int64

In [4]:
import numpy as np
import pandas as pd

df = pd.read_csv("Numeric data (last year work).csv")

variable = "Year"

# Calculate the median
median = df[variable].median()

# Calculate MAD
mad = np.median(np.abs(df[variable] - median))

# Define a threshold for noise detection
threshold = 3 * mad

# Detect noise
noise = df[np.abs(df[variable] - median) > threshold]

print("Detected noise using MAD:")
noise

Detected noise using MAD:

,Rating,Votes,Meta Score,Year,Duration,Action,Adventure,Animation,Biography,Comedy,...,PG Rating_NC-17,PG Rating_PG,PG Rating_PG-13,PG Rating_Passed,PG Rating_R,PG Rating_TV-14,PG Rating_TV-G,PG Rating_TV-MA,PG Rating_TV-PG,PG Rating_TV-Y7
222,7.4,128000.0,79.0,1978,109,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
350,7.4,185000.0,82.0,1978,143,1,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
358,7.2,295000.0,70.0,1978,110,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
372,6.8,218000.0,73.0,1979,88,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
397,7.7,256000.0,78.0,1980,88,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
643,7.5,109000.0,65.0,1979,93,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
658,7.2,125000.0,48.0,1980,98,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
703,8.1,373000.0,90.0,1980,129,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
746,7.1,19000.0,56.0,1978,91,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
756,6.2,107000.0,66.0,1979,126,1,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
870,7.9,210000.0,60.0,1980,133,1,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
968,8.0,418000.0,77.0,1979,94,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
993,7.7,302000.0,87.0,1978,91,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1004,6.5,12000.0,66.0,1978,110,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1023,6.9,13000.0,68.0,1980,100,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
1092,6.5,60000.0,58.0,1980,111,1,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [ ]:
# The outliers listed are primarily from 1978 and 1979.
# But in the next cell, I checked the unique values
# and their amount in the data.
# I do not understand why the MAD test did not show
# 1983 - 6
# 1980 - 6
# because they have the same number of data points as the ones
# who are placed in the table below.

# But! Maybe the table has a limitation in rows.

# I checked why this happened.
# The reason the years 1983 and 1980 were not flagged as outliers, 
# even though they have the same quantity of data points 
# as other years (like 1978 and 1979), is because the MAD focuses 
# on the deviation from the median value rather 
# than the frequency of each year in the dataset.

In [8]:
df['Year'].value_counts()

Year
2023    120
2022     75
2019     53
2021     52
2018     41
2015     41
2016     41
2017     39
2010     32
2020     30
2004     29
2012     27
2014     26
2011     26
2001     24
2005     23
1999     22
2009     22
2008     22
2000     22
2006     21
1997     21
2003     21
1987     21
1993     20
2002     19
2007     19
1985     19
1994     18
1996     17
1995     16
1992     16
1998     15
1989     15
1984     13
1988     12
2013     12
1991     12
1986     11
1990      9
1981      8
1982      7
1978      6
1983      6
1980      6
1979      4
Name: count, dtype: int64